name: WordCloud

on:
  push:
    branches: ["main"]
  # update wordcloud if has pull_request
  # pull_request:
    # branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure Git
      env:
        GIT_USERNAME: ${{ secrets.NAME }}
        GIT_EMAIL: ${{ secrets.EMAIL }}
      run: |
        git config --global user.name "${GIT_USERNAME}"
        git config --global user.email "${GIT_EMAIL}"
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install packages
      run: |
        npm install
    - name: Update wordcloud
      run: |
        node src/index.js
    - name: Push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
